url: "https://paelladoc.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
title: "Vibe Coding with Cursor as a Pro - PAELLADOC" # the name of your site
description: "Transform your coding experience with PAELLADOC - The ultimate AI-powered development framework that makes your team's workflow mucho mejor."
author: "PAELLADOC Team"
email: "contact@paelladoc.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-responsive-image

# Configuración del plugin jekyll-responsive-image
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 320
    - width: 480
    - width: 768
    - width: 1024
    - width: 1200
    - width: 1920
  base_path: _posts_images_original   # Carpeta para imágenes originales
  output_path_format: assets/images/responsive/:basename_:width.:extension  # Formato de salida simplificado
  save_to_source: false
  strip: true
  quality: 85
  formats:
    - webp
    - avif
  gravity: center
  default_quality: 90

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - .nojekyll # Exclude this too if present
  - generate-images.js # Ya no se necesita
  - package.json
  - package-lock.json

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:title/

# Blog settings
paginate: 6
paginate_path: "/blog/page:num/"
permalink: /blog/:title/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "PAELLADOC Team"
      avatar: "/assets/images/paelladoc-avatar.png"
      github: "https://github.com/jlcases"

# Category settings
category_archive:
  enabled: true
  path: "/blog/categories/"

# Cache settings
sass:
  style: compressed

# Custom headers for resources
webrick:
  headers:
    "Cache-Control": "max-age=31536000, public, immutable"

# Jekyll Responsive Image Configuration
