url: "https://paelladoc.com" # the base hostname & protocol for your site, leave empty for development
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Ultimate AI-First Development Framework | PAELLADOC" # the name of your site
description: "Transform your AI development process with a comprehensive framework that makes AI projects sustainable, transparent and efficient. From ideation to deployment, build AI products that scale with confidence."
author: "PAELLADOC Team"
email: "contact@paelladoc.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - .nojekyll # Exclude this too if present
  - generate-images.js # Ya no se necesita
  - package.json
  - package-lock.json
  - assets/images/posts
  - _site/assets/images/posts

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
  categories:
    output: true
    permalink: /blog/categories/:name/
  tags:
    output: true
    permalink: /blog/tags/:name/

# Pagination settings (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Category and tag settings
category_archive:
  enabled: true
  path: "/blog/categories"
  layout: "category"
  permalinks:
    category: /blog/categories/:name/

tag_archive:
  enabled: true
  path: "/blog/tags"
  layout: "tag"
  permalinks:
    tag: /blog/tags/:name/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "@jlcases"
      avatar: "/assets/images/avatarjl.jpg"
      github: "https://github.com/jlcases"
  -
    scope:
      path: "blog/categories"
      type: "pages"
    values:
      layout: "category"
      permalink: /blog/categories/:name/
  -
    scope:
      path: "blog/tags"
      type: "pages"
    values:
      layout: "tag"
      permalink: /blog/tags/:name/

# Cache settings
sass:
  style: compressed

# Custom headers for resources
webrick:
  headers:
    "Cache-Control": "max-age=31536000, public, immutable"

# Jekyll Responsive Image Configuration # Comentar todo este bloque
# responsive_image:
#   template: _includes/responsive-image.html
#   sizes:
#     - width: 320
#     - width: 480
#     - width: 768
#     - width: 1024
#     - width: 1200
#   base_path: assets/images
#   output_path_format: assets/images/%{filename}_%{width}.%{extension}
#   save_to_source: false
#   cache: true
#   cache_dir: .jekyll-cache/responsive-image
#   strip: true
#   extra_images:
#     - assets/images/*/*.{jpg,jpeg,png}
#     - assets/images/*.{jpg,jpeg,png}
#   ignore_missing_images: true
#   ignore_baseurl_prefix: true
#   formats: [webp, avif, original]
#   quality: 85
#   auto_rotate: true
#   gravity: center
#   skip_processing: false
#   skip_pattern: "(_[0-9]+\\.|_resized_|_processed_)"
#   process_original: true
#   regenerate_max_age: 2592000
#   check_for_updates: false
#   force_regeneration: true
#   use_cache: true
#   cache_policy: aggressive

# Añadir esto al archivo de configuración
# future: true # Comentado si solo era para el plugin
