name: Optimize Images (Manual)

on:
  workflow_dispatch:
    # Solo se ejecutará manualmente desde la interfaz de GitHub Actions
  
# Ya no se ejecutará automáticamente en push o pull request
# on:
#   push:
#     paths:
#       - 'assets/images/**'
#   pull_request:
#     paths:
#       - 'assets/images/**'

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g sharp-cli
          npm install -g svgo

      - name: Process Images
        run: |
          # Crear directorios si no existen
          mkdir -p assets/images/responsive

          # Procesar todas las imágenes en assets/images
          for img in assets/images/*.{jpg,jpeg,png,webp}; do
            if [ -f "$img" ]; then
              filename=$(basename "$img")
              name="${filename%.*}"
              ext="${filename##*.}"
              
              # Crear versiones WebP para diferentes dispositivos
              # 320px - Móviles pequeños
              # 480px - Móviles
              # 768px - Tablets
              # 1024px - Laptops
              # 1200px - Desktops
              # 1920px - Pantallas grandes
              for size in 320 480 768 1024 1200 1920; do
                sharp "$img" \
                  --resize "$size" \
                  --format webp \
                  --quality 85 \
                  --output "assets/images/responsive/${name}_${size}.webp"
              done

              # Crear versión AVIF para navegadores modernos
              for size in 320 480 768 1024 1200 1920; do
                sharp "$img" \
                  --resize "$size" \
                  --format avif \
                  --quality 80 \
                  --output "assets/images/responsive/${name}_${size}.avif"
              done
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add assets/images/responsive/
          git commit -m "chore: optimize and generate responsive images" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} 